"""Repository interface. Two implementations: LocalRepository, SupabaseRepository.
Selected by DATA_SOURCE=local|supabase. Screens & pipeline never change."""
from __future__ import annotations

from typing import Any, Optional, Protocol

from app.domain.models import (
    Company,
    DocumentStatus,
    Escalation,
    LeaseRecord,
    License,
    PassportVerification,
    Person,
    RunSummary,
    StageResult,
)


class Repository(Protocol):
    # Reads (via v_* views)
    def list_companies(self) -> list[Company]: ...
    def get_company(self, sr: str) -> Optional[Company]: ...
    def get_company_by_id(self, company_id: str) -> Optional[Company]: ...
    def get_people(self, company_id: str) -> list[Person]: ...
    def get_document_status(self, company_id: str) -> list[DocumentStatus]: ...
    def get_passport_verifications(self, company_id: str) -> list[PassportVerification]: ...
    def get_run(self, run_id: str) -> Optional[RunSummary]: ...
    def get_escalations(self, run_id: str) -> list[Escalation]: ...
    def get_lease(self, company_id: str) -> Optional[LeaseRecord]: ...
    def get_license(self, company_id: str) -> Optional[License]: ...
    def get_audit(self, company_id: str) -> list[dict[str, Any]]: ...

    # Writes (base tables)
    def upsert_upload(self, company_id: str, doc_key: str, source: str, filename: str,
                      path: str, fields: dict, status: str) -> None: ...
    def save_passport_verification(self, pv: PassportVerification) -> str: ...
    def create_run(self, company_id: str) -> str: ...
    def finish_run(self, run_id: str, status: str, summary: dict) -> None: ...
    def save_stage_result(self, run_id: str, sr: StageResult) -> None: ...
    def create_escalation(self, run_id: str, level: str) -> str: ...
    def set_escalation(self, run_id: str, level: str, status: str, by: str) -> None: ...
    def save_lease(self, rec: LeaseRecord) -> None: ...
    def save_license(self, lic: License) -> None: ...
    def set_company_status(self, company_id: str, status: str) -> None: ...
    def upsert_verification(self, company_id: str, sr: str, name: str, status: str,
                            verified: bool, run_id: str, reason: str) -> None: ...
    def list_verifications(self) -> list[dict[str, Any]]: ...
    def audit(self, **kw) -> None: ...
